# Generated by Django 4.1.1 on 2022-10-04 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipesmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipesmodel',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='recipesmodel',
            name='number_of_dishes',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='recipesmodel',
            name='ingredients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredients'),
            preserve_default=False,
        ),
    ]
